apiVersion: argoproj.io/v1alpha1
kind: Application
# https://dev.local.me/demo-gateway-client2/config/topics
metadata:
  name: demo-gateway-client2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    path: demo-gateway-client2-chart
    repoURL: https://github.com/manumura/demo-spring-gateway-charts.git
    targetRevision: master
    helm:
      releaseName: demo-gateway-client2-release
      valueFiles:
        - environments/values.dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true