apiVersion: argoproj.io/v1alpha1
kind: Application
# https://dev.local.me/demo-gateway-client1/config/topics
metadata:
  name: demo-gateway-client1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: default
  source:
    path: demo-gateway-client1-chart
    repoURL: https://github.com/manumura/demo-spring-gateway-charts.git
    targetRevision: master
    helm:
      releaseName: demo-gateway-client1-release
      valueFiles:
        - environments/values.dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true