apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-appproject
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: The root app project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  # Only permit applications to deploy to specific namespace in the same cluster
  destinations:
    - namespace: '*'
      server: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  orphanedResources:
    warn: false