apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: kube-prometheus
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.7.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
